lessc palette.less > ../css/palette.css
lessc carousel.less > ../css/carousel.css
lessc comments.less > ../css/comments.css
lessc flexslider.less > ../css/flexslider.css
lessc lof-slider.less > ../css/lof-slider.css
lessc forms.less > ../css/forms.css
lessc lessframework.less > ../css/lessframework.css
lessc shortcodes.less > ../css/shortcodes.css
lessc skin.less > ../css/skin.css
lessc style.less > ../css/style.css
lessc widgets.less > ../css/widgets.css
